
export default [
            {
                "olson_path": "America/Chicago",
                "region_abbr": "AL",
                "postal_code": "35233",
                "latitude": "33.508914",
                "id": "E0-001-112741313-6",
                "city_name": "Birmingham",
                "longitude": "-86.79786",
                "country_name": "United States",
                "country_abbr": "USA",
                "region_name": "Alabama",
                "start_time": "2018-06-01 20:00:00",
                "description": null,
                "modified": "2018-03-13 17:16:09",
                "venue_display": "1",
                "performers": null,
                "title": "New York Bee Gees",
                "venue_address": "513 22nd Street South",
                "geocode_type": "EVDB Geocoder",
                "owner": "evdb",
                "country_abbr2": "US",
                "image": null,
                "created": "2018-03-12 16:21:25",
                "venue_id": "V0-001-006341645-4",
                "venue_name": "Iron City",
            },
            {
                "olson_path": "America/Chicago",
                "region_abbr": "AL",
                "postal_code": "35203",
                "latitude": "33.5249829",
                "id": "E0-001-111509496-5",
                "city_name": "Birmingham",
                "longitude": "-86.8134216",
                "country_name": "United States",
                "country_abbr": "USA",
                "region_name": "Alabama",
                "start_time": "2018-06-26 19:30:00",
                "description": null,
                "modified": "2018-05-01 07:35:17",
                "venue_display": "1",
                "performers": null,
                "title": "David Lee Ultimate Elvis",
                "venue_address": "1001 19th Street North",
                "geocode_type": "EVDB Geocoder",
                "owner": "evdb",
                "country_abbr2": "US",
                "image": {
                    "block100": {
                        "width": "100",
                        "url": "//d1marr3m5x4iac.cloudfront.net/images/block100/I0-001/032/796/946-3.jpeg_/david-lee-ultimate-elvis-46.jpeg",
                        "height": "100"
                    },
                    "blackborder250": {
                        "width": "250",
                        "url": "//d1marr3m5x4iac.cloudfront.net/images/blackborder250/I0-001/032/796/946-3.jpeg_/david-lee-ultimate-elvis-46.jpeg",
                        "height": "250"
                    }
                },
                "created": "2018-02-09 21:08:43",
                "venue_id": "V0-001-000153948-3",
                "venue_name": "Legacy Arena at the BJCC",
            },
            {
                "olson_path": "America/Chicago",
                "region_abbr": "AL",
                "postal_code": "35233",
                "latitude": "33.508914",
                "id": "E0-001-114022061-4",
                "city_name": "Birmingham",
                "longitude": "-86.79786",
                "country_name": "United States",
                "country_abbr": "USA",
                "region_name": "Alabama",
                "start_time": "2018-06-08 20:00:00",
                "description": " Brockhampton is an American hip hop collective formed in San Marcos, Texas in 2015. The self-stylised &#39;boy band&#39; was founded on Internet forum KanyeToThe, leading them to be described as &#39;The Internet&#39;s first boy band&#39;.<br><br>There are currently no videos. Check back soon.<br><br>BROCKHAMPTON - Sold OutIron City - ShowsJune 8, 2018<p>Don’t let “sold out” dash your hopes! Check our ticket exchange, powered by Lyte, a no-hassle sweet spot where you can securely buy or sell tickets.<a href=\"https://uselyte.com/ticketfly/exchange/1663300\" rel=\"nofollow\">Find fan tickets</a></p>",
                "modified": "2018-04-28 19:29:50",
                "venue_display": "1",
                "performers": null,
                "title": "Sold Out: BROCKHAMPTON - Sold Out",
                "venue_address": "513 22nd Street South",
                "geocode_type": "EVDB Geocoder",
                "owner": "evdb",
                "country_abbr2": "US",
                "image": null,
                "created": "2018-04-28 13:15:28",
                "venue_id": "V0-001-006341645-4",
                "venue_name": "Iron City",
            },
            {
                "olson_path": "America/Chicago",
                "region_abbr": "AL",
                "postal_code": "35205",
                "latitude": "33.4967700",
                "id": "E0-001-114268428-7",
                "city_name": "Birmingham",
                "longitude": "-86.8077850",
                "country_name": "United States",
                "country_abbr": "USA",
                "region_name": "Alabama",
                "start_time": "2018-06-22 20:00:00",
                "description": "Nora Jane Struthers has written &quot;some of the most quietly powerful narratives within the new wave of Americana artists&quot; - NPR Music. The songs that weave themselves into the fabric of listeners&#39; lives are usually the ones in which an artist lays her soul bare for the world to hear. Struthers&#39; new album Champion, is built on these kinds of songs. The 13-song collection written with her band the Party Line, is the follow-up to 2015&#39;s Wake, which earned Struthers acclaim from major outlets like NPR Music, Rolling Stone Country, and &quot;Fresh Air&quot; and their Live show is full to the brim with stellar musicianship, unexpected arrangements that blur the lines between folk, roots, and rock, and an audible sense that everyone in the room is having a damn good time.",
                "modified": "2018-05-09 05:23:29",
                "venue_display": "1",
                "performers": null,
                "title": "Nora Jane Struthers & The Party Line",
                "venue_address": "1200 10th Ave South",
                "geocode_type": "EVDB Geocoder",
                "owner": "Melfarina",
                "country_abbr2": "US",
                "image": {
                    "block100": {
                        "width": "100",
                        "url": "//d1marr3m5x4iac.cloudfront.net/images/block100/I0-001/040/185/635-1.jpeg_/nora-jane-struthers-party-line-35.jpeg",
                        "height": "100"
                    },
                    "blackborder250": {
                        "width": "250",
                        "url": "//d1marr3m5x4iac.cloudfront.net/images/blackborder250/I0-001/040/185/635-1.jpeg_/nora-jane-struthers-party-line-35.jpeg",
                        "height": "250"
                    }
                },
                "created": "2018-05-09 05:23:29",
                "venue_id": "V0-001-000599786-1",
                "venue_name": "UAB's Alys Stephens Center",
            },
            {
                "olson_path": "America/Chicago",
                "region_abbr": "AL",
                "postal_code": "35216",
                "latitude": "33.4140776",
                "id": "E0-001-114248528-8",
                "city_name": "Birmingham",
                "longitude": "-86.8078079",
                "country_name": "United States",
                "country_abbr": "USA",
                "region_name": "Alabama",
                "start_time": "2018-06-23 20:30:00",
                "description": null,
                "modified": "2018-05-08 18:06:27",
                "venue_display": "1",
                "performers": null,
                "title": "Hobo Johnson (18+ Event)",
                "venue_address": "3010 Columbiana Rd",
                "geocode_type": "EVDB Geocoder",
                "owner": "evdb",
                "country_abbr2": "US",
                "image": null,
                "created": "2018-05-08 18:06:27",
                "venue_id": "V0-001-008942173-9",
                "venue_name": "Saturn",
            },
            {
                "olson_path": "America/Chicago",
                "region_abbr": "AL",
                "postal_code": "35216",
                "latitude": "33.4140776",
                "id": "E0-001-114085012-3",
                "city_name": "Birmingham",
                "longitude": "-86.8078079",
                "country_name": "United States",
                "country_abbr": "USA",
                "region_name": "Alabama",
                "start_time": "2018-06-02 21:00:00",
                "description": null,
                "modified": "2018-05-02 22:37:46",
                "venue_display": "1",
                "performers": null,
                "title": "Great Good Fine OK",
                "venue_address": "3010 Columbiana Rd",
                "geocode_type": "EVDB Geocoder",
                "owner": "evdb",
                "country_abbr2": "US",
                "image": null,
                "created": "2018-05-02 22:37:46",
                "venue_id": "V0-001-008942173-9",
                "venue_name": "Saturn",
                "venue_url": "http://birmingham.eventful.com/venues/saturn-/V0-001-008942173-9?utm_source=apis&utm_medium=apim&utm_campaign=apic"
            },
            {
                "olson_path": "America/Chicago",
                "region_abbr": "AL",
                "postal_code": "35205",
                "latitude": "33.5054018",
                "id": "E0-001-113663074-4",
                "city_name": "Birmingham",
                "longitude": "-86.7904843",
                "country_name": "United States",
                "country_abbr": "USA",
                "region_name": "Alabama",
                "start_time": "2018-07-01 22:00:00",
                "description": " <br> ",
                "modified": "2018-04-11 08:54:51",
                "venue_display": "1",
                "performers": null,
                "title": "Lesser Glow, Kamikaze Zombie, Mountain Bastard",
                "venue_address": "2514 10th Avenue South",
                "geocode_type": "EVDB Geocoder",
                "owner": "evdb",
                "country_abbr2": "US",
                "image": null,
                "created": "2018-04-11 08:54:51",
                "venue_id": "V0-001-000885124-1",
                "venue_name": "The Nick",
            },
            {
                "olson_path": "America/Chicago",
                "region_abbr": "AL",
                "postal_code": "35205",
                "latitude": "33.5054018",
                "id": "E0-001-113666075-4",
                "city_name": "Birmingham",
                "longitude": "-86.7904843",
                "country_name": "United States",
                "country_abbr": "USA",
                "region_name": "Alabama",
                "start_time": "2018-06-28 22:00:00",
                "description": " <br> Hip-Hop from Eden VT",
                "modified": "2018-04-11 09:56:03",
                "venue_display": "1",
                "performers": null,
                "title": "Khaosity",
                "venue_address": "2514 10th Avenue South",
                "geocode_type": "EVDB Geocoder",
                "owner": "evdb",
                "country_abbr2": "US",
                "image": null,
                "created": "2018-04-11 09:56:03",
                "venue_id": "V0-001-000885124-1",
                "venue_name": "The Nick",
            },
            {
                "olson_path": "America/Chicago",
                "region_abbr": "AL",
                "postal_code": "35205",
                "latitude": "33.5054018",
                "id": "E0-001-113666016-1",
                "city_name": "Birmingham",
                "longitude": "-86.7904843",
                "country_name": "United States",
                "country_abbr": "USA",
                "region_name": "Alabama",
                "start_time": "2018-06-17 22:00:00",
                "description": " <br> ",
                "modified": "2018-04-26 04:36:37",
                "venue_display": "1",
                "performers": null,
                "title": "Why Not, Seismos, RATOBaby",
                "venue_address": "2514 10th Avenue South",
                "geocode_type": "EVDB Geocoder",
                "owner": "evdb",
                "country_abbr2": "US",
                "image": null,
                "created": "2018-04-11 09:55:03",
                "venue_id": "V0-001-000885124-1",
                "venue_name": "The Nick",
            },
            {
                "olson_path": "America/Chicago",
                "region_abbr": "AL",
                "postal_code": "35233",
                "latitude": "33.509863",
                "id": "E0-001-112893438-0",
                "city_name": "Birmingham",
                "longitude": "-86.7975619",
                "country_name": "United States",
                "country_abbr": "USA",
                "region_name": "Alabama",
                "start_time": "2018-06-30 18:30:00",
                "description": " <br><strong><a href=\"http://www.workplay.com/wp-content/uploads/2018/03/Envoy-concert1.jpg\" rel=\"nofollow\"></a></strong><br><p></p>",
                "modified": "2018-03-17 17:03:57",
                "venue_display": "1",
                "performers": null,
                "title": "Ken & Envoy Single Release Concert: The Sound of the Journey",
                "venue_address": "500 23rd St S",
                "geocode_type": "EVDB Geocoder",
                "owner": "evdb",
                "country_abbr2": "US",
                "image": {
                    "block100": {
                        "width": "100",
                        "url": "//d1marr3m5x4iac.cloudfront.net/images/block100/I0-001/039/970/995-6.jpeg_/ken-envoy-single-release-concert-sound-journey-95.jpeg",
                        "height": "100"
                    },
                    "blackborder250": {
                        "width": "250",
                        "url": "//d1marr3m5x4iac.cloudfront.net/images/blackborder250/I0-001/039/970/995-6.jpeg_/ken-envoy-single-release-concert-sound-journey-95.jpeg",
                        "height": "250"
                    }
                },
                "created": "2018-03-17 08:13:44",
                "venue_id": "V0-001-001125136-2",
                "venue_name": "WorkPlay Theatre",
            },
            {
                "olson_path": "America/Chicago",
                "region_abbr": "AL",
                "postal_code": "35233",
                "latitude": "33.508914",
                "id": "E0-001-112823123-8",
                "city_name": "Birmingham",
                "longitude": "-86.79786",
                "country_name": "United States",
                "country_abbr": "USA",
                "region_name": "Alabama",
                "start_time": "2018-06-08 20:00:00",
                "description": null,
                "modified": "2018-03-15 22:06:23",
                "venue_display": "1",
                "performers": null,
                "title": "Brockhampton",
                "venue_address": "513 22nd Street South",
                "geocode_type": "EVDB Geocoder",
                "owner": "evdb",
                "country_abbr2": "US",
                "image": null,
                "created": "2018-03-15 12:53:47",
                "venue_id": "V0-001-006341645-4",
                "venue_name": "Iron City",
            },
            {
                "olson_path": "America/Chicago",
                "region_abbr": "AL",
                "postal_code": "35205",
                "latitude": "33.5054018",
                "id": "E0-001-113786453-3",
                "city_name": "Birmingham",
                "longitude": "-86.7904843",
                "country_name": "United States",
                "country_abbr": "USA",
                "region_name": "Alabama",
                "start_time": "2018-06-10 22:00:00",
                "description": null,
                "modified": "2018-04-17 21:01:28",
                "venue_display": "1",
                "performers": null,
                "title": "Jeff Kujan and RatoBaby (21+ Event)",
                "venue_address": "2514 10th Avenue South",
                "geocode_type": "EVDB Geocoder",
                "owner": "evdb",
                "country_abbr2": "US",
                "image": null,
                "created": "2018-04-17 21:01:28",
                "venue_id": "V0-001-000885124-1",
                "venue_name": "The Nick",
            },
            {
                "olson_path": "America/Chicago",
                "region_abbr": "AL",
                "postal_code": "35226",
                "latitude": "33.41178",
                "id": "E0-001-113561154-8",
                "city_name": "Birmingham",
                "longitude": "-86.856333",
                "country_name": "United States",
                "country_abbr": "USA",
                "region_name": "Alabama",
                "start_time": "2018-06-08 19:30:00",
                "description": null,
                "modified": "2018-04-05 16:35:54",
                "venue_display": "1",
                "performers": null,
                "title": "Grant Peeples- Jaimee Harris",
                "venue_address": "585 Shades Crest Rd",
                "geocode_type": "EVDB Geocoder",
                "owner": "evdb",
                "country_abbr2": "US",
                "image": null,
                "created": "2018-04-05 16:35:54",
                "venue_id": "V0-001-004007923-6",
                "venue_name": "Moonlight on the Mountain",
            },
            {
                "olson_path": "America/Chicago",
                "region_abbr": "AL",
                "postal_code": "35244",
                "latitude": "33.3701098",
                "id": "E0-001-113828318-8",
                "city_name": "Birmingham",
                "longitude": "-86.7969713",
                "country_name": "United States",
                "country_abbr": "USA",
                "region_name": "Alabama",
                "start_time": "2018-06-02 20:00:00",
                "description": null,
                "modified": "2018-04-19 20:31:57",
                "venue_display": "1",
                "performers": null,
                "title": "Phil Denny",
                "venue_address": "1845 Montgomery Highway",
                "geocode_type": "EVDB Geocoder",
                "owner": "evdb",
                "country_abbr2": "US",
                "image": null,
                "created": "2018-04-19 20:31:57",
                "venue_id": "V0-001-010313225-4",
                "venue_name": "Perfect Note",
            },
            {
                "olson_path": "America/Chicago",
                "region_abbr": "AL",
                "postal_code": "35205",
                "latitude": "33.5054018",
                "id": "E0-001-113783801-5",
                "city_name": "Birmingham",
                "longitude": "-86.7904843",
                "country_name": "United States",
                "country_abbr": "USA",
                "region_name": "Alabama",
                "start_time": "2018-06-29 22:00:00",
                "description": null,
                "modified": "2018-04-17 12:55:39",
                "venue_display": "1",
                "performers": null,
                "title": "Happy Lemmy (21+ Event)",
                "venue_address": "2514 10th Avenue South",
                "geocode_type": "EVDB Geocoder",
                "owner": "evdb",
                "country_abbr2": "US",
                "image": null,
                "created": "2018-04-17 12:55:39",
                "venue_id": "V0-001-000885124-1",
                "venue_name": "The Nick",
            },
            {
                "olson_path": "America/Chicago",
                "region_abbr": "AL",
                "postal_code": "35205",
                "latitude": "33.5054018",
                "id": "E0-001-113807030-8",
                "city_name": "Birmingham",
                "longitude": "-86.7904843",
                "country_name": "United States",
                "country_abbr": "USA",
                "region_name": "Alabama",
                "start_time": "2018-06-27 22:00:00",
                "description": null,
                "modified": "2018-04-18 19:47:36",
                "venue_display": "1",
                "performers": null,
                "title": "The Plott Hounds (21+ Event)",
                "venue_address": "2514 10th Avenue South",
                "geocode_type": "EVDB Geocoder",
                "owner": "evdb",
                "country_abbr2": "US",
                "image": null,
                "created": "2018-04-18 19:47:36",
                "venue_id": "V0-001-000885124-1",
                "venue_name": "The Nick",
            },
            {
                "olson_path": "America/Chicago",
                "region_abbr": "AL",
                "postal_code": "35233",
                "latitude": "33.508914",
                "id": "E0-001-113501715-9",
                "city_name": "Birmingham",
                "longitude": "-86.79786",
                "country_name": "United States",
                "country_abbr": "USA",
                "region_name": "Alabama",
                "start_time": "2018-06-15 20:00:00",
                "description": " with Abby Anderson<br> Russell Dickerson was born for the stage. Im just naturally that kind of dude: a big, loud and over-the-top guy, he says with a laugh. Yes, one of country musics most talked-about new talents -- and the voice behind the smash single Yours, a stunning ballad inspired by his wife of four years, Kailey, thats racked up over 33 million streams to date on Spotify, where hes been on the Hot Country, Country Gold Playlists and more for over a year, and exploded since being serviced to country radio in April -- need not go into entertainer mode before he catapults himself onstage to deliver one of his notoriously amped-up live shows.Hes already there.I go out there, and Im just me, Dickerson, who recently tore up arenas with Thomas Rhett and Kelsea Ballerini on the Home Team Tour, says. Watch the massive-voiced singer up there, whipping the crowd into hysterics and performing with that time-honored killer instinct. Hes running around and singing to people and messing with them and loving on them. Its about interacting the whole time. I want people screaming their faces off. Its all for the crowd.Even as a Union City, Tennessee-raised, obsessive teenage music fan, one whod regularly wait in wraparound lines to see his favorite artists perform in Nashville (I just got hooked on that energy) and held up Garth Brooks and Keith Urban DVDs as his personal Gospel, Dickerson, says being that dude onstage was always the dream. We would scream every word of every song, and all I could think about was I want to be that guy! Now, thanks to Yours and hook-heavy rockers like Blue Tacoma and MGNO, hes steadily built a serious fan base of his own.Strident, proud and fiercely determined in his artistry, Dickerson is that rare breed of artist who both writes with patient, staid intention and performs like a kid living out his wildest fantasy. Ive always envisioned myself playing stadiums. Honestly, as big as it will go, man, says the singer/songwriter who saw Yours explode on satellite radio and streaming services alike after Dickerson released his Billboard charting EP. The songs success led his manager at Dennis Entertainment to introduce him to the newly formed Triple Tigers, a joint venture with Sony Music, in October 2016 where he became the flagship artist.Now, with his forthcoming full-length debut album, Yours, Dickerson is gearing up for his most massive moment yet. Right now Im just so stoked on life so I wanted my record to mimic that, the 30-year-old says of a feel-good album stuffed with equal parts swagger (Billions, Float) and sweet vibes (All Fall Down, You Look Like A Love Song). We just kept rolling with it, he says of the loose, freewheeling writing sessions for the LP. To that end, if theres a palpable ease and whimsical flow to Dickersons melodies and lyrics its because hes found trusted collaborators, the most notable of which is his wife.It was Kailey, in fact, who not only inspired Yours but also dreamed up the idea for its stunning video. On a rainy day back in 2015, the Dickersons drove out near John C. Tune Airport and, with Russell strolling behind his car for what he thought was merely test footage, Kailey began filming. This spur-of-the-moment adventure that cost only the $6 required for gas money wound up producing the massively successful beautiful black-and-white music video for Dickersons breakout hit. To date, the video for Yours has been viewed more than three million times on YouTube. Its experiences like this, not to mention a fruitful writing partnership with longtime friends and fellow Belmont University graduates Parker Welling and Casey Brown, that has Dickerson feeling so inspired. Were just young kids writing relevant music, he says. And having all known each other for years, as well as seeing Russell and Kaileys relationship blossom, the trio all felt connected to Yours. Since then, theyve teamed to write the majority of the songs on his upcoming album as well. Its just cool to write with friends, Dickerson says. Its way less pressure and I can be myself. We just have this deeper connection.Its a feeling not dissimilar from one hes long held for music on the whole. The son of a piano-teaching mother and church choir-leading father, Dickerson was constantly surrounded by songs as a child. It was all around me, he remembers of an idyllic childhood. Dickerson credits discovering classic country artists like George Jones and Jim Reeves later in life as inspiring him to eventually pursue a career as a country music singer/songwriter. By the time he enrolled at Belmont and fell in with a group of hungry young musicians, he knew hed found his calling. It was really natural and young and innocent and we were having fun making music, he recalls.Dickerson says hed written hundreds of songs before that gut feeling kicked in one day in 2014 when he, Welling and Brown penned Yours. When we wrote it we all said This is amazing! And then it was just one thing after another, he says of the songs rocketship ride to radio. To get that affirmation from everyone at, what felt like, every step publishers, record label, radio is just so incredible. Adds Dickerson of the breakout song, which has become a wedding standard, and because of which he recorded an acoustic wedding version: Its such a boost of confidence. Its validation.Still, even as the accomplishments pile up, including the distinct honor of playing at the Grand Ole Opry last June (To be recognized for my craft by an establishment thats so esteemed in the industry was emotional), Dickerson remains steadfast in his pursuit of refining his craft and taking his career to new heights.For as long as weve prepped for this, Dickerson says, I hope this is just the beginning.",
                "modified": "2018-05-03 11:14:05",
                "venue_display": "1",
                "performers": {
                    "performer": {
                        "creator": "evdb",
                        "linker": "evdb",
                        "name": "Russell Dickerson",
                        "url": "http://concerts.eventful.com/Russell-Dickerson?utm_source=apis&utm_medium=apim&utm_campaign=apic",
                        "id": "P0-001-000283910-4",
                        "short_bio": "Country"
                    }
                },
                "title": "Russell Dickerson",
                "venue_address": "513 22nd Street South",
                "geocode_type": "EVDB Geocoder",
                "owner": "evdb",
                "country_abbr2": "US",
                "image": {
                    "block100": {
                        "width": "100",
                        "url": "//d1marr3m5x4iac.cloudfront.net/images/block100/I0-001/004/361/766-6.jpeg_/russell-dickerson-66.jpeg",
                        "height": "100"
                    },
                    "blackborder250": {
                        "width": "250",
                        "url": "//d1marr3m5x4iac.cloudfront.net/images/blackborder250/I0-001/004/361/766-6.jpeg_/russell-dickerson-66.jpeg",
                        "height": "250"
                    }
                },
                "created": "2018-04-03 09:47:12",
                "venue_id": "V0-001-006341645-4",
                "venue_name": "Iron City",
            },
            {
                "olson_path": "America/Chicago",
                "region_abbr": "AL",
                "postal_code": "35222",
                "latitude": "33.524291",
                "id": "E0-001-113310414-1",
                "city_name": "Birmingham",
                "longitude": "-86.7744642",
                "country_name": "United States",
                "country_abbr": "USA",
                "region_name": "Alabama",
                "start_time": "2018-06-08 21:00:00",
                "description": " with Terra Lightfoot<br> Rock n roll has rarely been as smart, soulful or satisfying than it has in the hands of The Posies. During an on/off career thats stretched across four decades, the Seattle-rooted outfit, led by musical polymaths Jon Auer and Ken Stringfellow, have shaped and re-shaped their muse, creating one of the more compelling catalogues in modern pop.With SOLID STATES, their 8th album, the Posies mark dramatic changes in the lives, the music, the evolution of the band.When the Posies long time drummer, Darius, died suddenly and unexpectedly last year, Posies founding members Jon Auer and Ken Stringfellow were devastated. Hard as it was to continue without such a close friend and great musician, the moment called for a reinvention. For now the idea of the band getting into a room and banging out the music, garage band style, was over. The ideas coming from Jon and Ken were fragile and the moods contemplative. Death, divorce, loss. Even the joys of life are fleeting enough as to be treated with care and respect.Of course, the Posies still retain their legendary melodic abilities, their trademark vocal harmonies and their lyrical agility. The band has always been exploring, growing. The multiyear gaps between albums are typically spent in countless other projects that bring new skills, sounds, experiences and people to the picture. The band will present the album live in a new format, incorporating laptop elements along with guitars, keyboards and drums. As artists, the band feels its their duty to take risks and explore.",
                "modified": "2018-03-28 19:17:46",
                "venue_display": "1",
                "performers": {
                    "performer": [
                        {
                            "creator": "chryme",
                            "linker": "evdb",
                            "name": "The Posies",
                            "url": "http://concerts.eventful.com/The-Posies?utm_source=apis&utm_medium=apim&utm_campaign=apic",
                            "id": "P0-001-000121182-4",
                            "short_bio": "peo"
                        },
                        {
                            "creator": "luvbone",
                            "linker": "evdb",
                            "name": "posies",
                            "url": "http://concerts.eventful.com/posies?utm_source=apis&utm_medium=apim&utm_campaign=apic",
                            "id": "P0-001-000006912-7",
                            "short_bio": "under appriciated Seattle band"
                        }
                    ]
                },
                "title": "The Posies",
                "venue_address": "200 41st Street S",
                "geocode_type": "EVDB Geocoder",
                "owner": "evdb",
                "country_abbr2": "US",
                "image": null,
                "created": "2018-03-28 19:17:46",
                "venue_id": "V0-001-008874407-7",
                "venue_name": "Saturn",
            },
            {
                "olson_path": "America/Chicago",
                "region_abbr": "AL",
                "postal_code": "35205",
                "latitude": "33.5054018",
                "id": "E0-001-113192728-3",
                "city_name": "Birmingham",
                "longitude": "-86.7904843",
                "country_name": "United States",
                "country_abbr": "USA",
                "region_name": "Alabama",
                "start_time": "2018-06-20 21:00:00",
                "description": " with Null<br> Young Widows celebrate the 10 year anniversary Old Wounds with a string of performances, playing the album in its entirety. Emma Ruth Rundle will be performing solo June 8th through 14th, Alexis Marshall (of the band Daughters) will be reading from his book as well as other poems June 9th through June 14th, and Null from Birmingham Alabama (members of Coliseum) will be performing June 15th through 21st. Looking forward.Young Widows&#39; bruising 2006 debut, Settle Down City, introduced the Louisville, KY trio as an ugly force to be reckoned with. Two years later they dropped Old Wounds, their sophomore stomp that inspired at least a dozen imitators of varying degrees of success. From there the band traded some of their trademark fury for the bleak, widescreen atmospheres of In and Out of Youth and Lightness. Now, three years later, Young Widows meld the strengths of their past and their tenacity for the future to forge Easy Pain, an album perfectly befitting their merciless moniker.",
                "modified": "2018-04-11 08:56:46",
                "venue_display": "1",
                "performers": {
                    "performer": {
                        "creator": "chuck",
                        "linker": "evdb",
                        "name": "Young Widows",
                        "url": "http://concerts.eventful.com/Young-Widows?utm_source=apis&utm_medium=apim&utm_campaign=apic",
                        "id": "P0-001-000009335-5",
                        "short_bio": "Music"
                    }
                },
                "title": "Young Widows",
                "venue_address": "2514 10th Avenue South",
                "geocode_type": "EVDB Geocoder",
                "owner": "evdb",
                "country_abbr2": "US",
                "image": null,
                "created": "2018-03-24 15:23:56",
                "venue_id": "V0-001-000885124-1",
                "venue_name": "The Nick",
            },
            {
                "olson_path": "America/Chicago",
                "region_abbr": "AL",
                "postal_code": "35205",
                "latitude": "33.497336",
                "id": "E0-001-114080161-3",
                "city_name": "Birmingham",
                "longitude": "-86.793077",
                "country_name": "United States",
                "country_abbr": "USA",
                "region_name": "Alabama",
                "start_time": "2018-06-08 21:30:00",
                "description": null,
                "modified": "2018-05-09 20:49:17",
                "venue_display": "1",
                "performers": null,
                "title": "Jobe Fortner W/ Tyler Braden & Clay Barker",
                "venue_address": "2001 15th Avenue South",
                "geocode_type": "EVDB Geocoder",
                "owner": "evdb",
                "country_abbr2": "US",
                "image": {
                    "block100": {
                        "width": "100",
                        "url": "//d1marr3m5x4iac.cloudfront.net/images/block100/I0-001/037/008/041-6.jpeg_/jobe-fortner-w-tyler-braden-clay-barker-41.jpeg",
                        "height": "100"
                    },
                    "blackborder250": {
                        "width": "250",
                        "url": "//d1marr3m5x4iac.cloudfront.net/images/blackborder250/I0-001/037/008/041-6.jpeg_/jobe-fortner-w-tyler-braden-clay-barker-41.jpeg",
                        "height": "250"
                    }
                },
                "created": "2018-05-02 18:05:00",
                "venue_id": "V0-001-000508203-5",
                "venue_name": "Zydeco",
            },
            {
                "olson_path": "America/Chicago",
                "region_abbr": "AL",
                "postal_code": "35203",
                "latitude": "33.5176283",
                "url": "http://birmingham.eventful.com/events/marc-harris-vibeville-fake-news-blooz-/E0-001-114523488-9?utm_source=apis&utm_medium=apim&utm_campaign=apic",
                "id": "E0-001-114523488-9",
                "city_name": "Birmingham",
                "longitude": "-86.8018758",
                "country_name": "United States",
                "country_abbr": "USA",
                "region_name": "Alabama",
                "start_time": "2018-06-08 21:30:00",
                "description": " Marc Harris performs with Fake News Blooz",
                "modified": "2018-05-15 22:21:14",
                "venue_display": "1",
                "performers": {
                    "performer": {
                        "creator": "John_R",
                        "linker": "evdb",
                        "name": "Marc Harris",
                        "url": "http://concerts.eventful.com/Marc-Harris?utm_source=apis&utm_medium=apim&utm_campaign=apic",
                        "id": "P0-001-000176766-0",
                        "short_bio": "Southern Surf"
                    }
                },
                "title": "Marc Harris & Vibeville- Fake News Blooz",
                "venue_address": "2308 2nd Avenue North",
                "geocode_type": "EVDB Geocoder",
                "owner": "evdb",
                "country_abbr2": "US",
                "image": null,
                "created": "2018-05-15 22:21:14",
                "venue_id": "V0-001-000354434-6",
                "venue_name": "Pale Eddie's Pour House",
            },
            {
                "olson_path": "America/Chicago",
                "region_abbr": "AL",
                "postal_code": "35222",
                "latitude": "33.5245451",
                "id": "E0-001-113915590-7",
                "city_name": "Birmingham",
                "longitude": "-86.7741712",
                "country_name": "United States",
                "country_abbr": "USA",
                "region_name": "Alabama",
                "start_time": "2018-06-30 20:00:00",
                "description": null,
                "modified": "2018-04-22 08:31:16",
                "venue_display": "1",
                "performers": {
                    "performer": {
                        "creator": "claydo1",
                        "linker": "evdb",
                        "name": "JJ Grey & Mofro",
                        "url": "http://concerts.eventful.com/JJ-Grey-Mofro?utm_source=apis&utm_medium=apim&utm_campaign=apic",
                        "id": "P0-001-000024777-0",
                        "short_bio": "Blues, Rock, Soul, R&B, Funk"
                    }
                },
                "title": "JJ Grey & Mofro",
                "venue_address": "201 41st Street South",
                "geocode_type": "EVDB Geocoder",
                "owner": "evdb",
                "country_abbr2": "US",
                "image": {
                    "block100": {
                        "width": "100",
                        "url": "//d1marr3m5x4iac.cloudfront.net/images/block100/I0-001/014/629/803-4.jpeg_/jj-grey-mofro-03.jpeg",
                        "height": "100"
                    },
                    "blackborder250": {
                        "width": "250",
                        "url": "//d1marr3m5x4iac.cloudfront.net/images/blackborder250/I0-001/014/629/803-4.jpeg_/jj-grey-mofro-03.jpeg",
                        "height": "250"
                    }
                },
                "created": "2018-04-22 08:31:16",
                "venue_id": "V0-001-011489941-6",
                "venue_name": "Avondale Brewing Co",
            },
            {
                "olson_path": "America/Chicago",
                "region_abbr": "AL",
                "postal_code": "35233",
                "latitude": "33.509863",
                "id": "E0-001-111554733-3",
                "city_name": "Birmingham",
                "longitude": "-86.7975619",
                "country_name": "United States",
                "country_abbr": "USA",
                "region_name": "Alabama",
                "start_time": "2018-06-07 20:00:00",
                "description": " <p><a href=\"http://www.workplay.com/wp-content/uploads/2018/02/alex-guthrie-sq-6x6.jpg\" rel=\"nofollow\"></a><p><strong><a href=\"http://www.alexguthriemusic.com/\" rel=\"nofollow\">Alex Guthrie</a></strong> is a singer-songwriter based in Atlanta. With the infusion of different genres such as soul, folk and rock, Guthrie brings audiences together through brilliant lyrics and an expressive voice.<p>Most recently, Guthrie has been noted as “the guy from the Jennifer Hudson commercial.” The now-infamous American Family Insurance <a href=\"https://www.youtube.com/watch?v=FpdKo6JnQJA\" rel=\"nofollow\">commercial</a> features him playing in Atlanta’s Woodruff Park when the Grammy Award-Winning singer and performer Jennifer Hudson surprises Guthrie and sings along to Bill Wither’s beloved “Lovely Day.” The commercial has played on national television and radio, resulting in new opportunities and heightened awareness for Alex Guthrie, his band and his music.<p>Guthrie and his band have performed events including <a href=\"https://www.youtube.com/watch?v=BRrPME6Qu50&feature=youtu.be\" rel=\"nofollow\">Milwaukee’s Summerfest</a> — which was also featured on <a href=\"http://www.jimmykimmellivemusic.com/videos/american-family-insurance-summerfest-recap-4\" rel=\"nofollow\">Jimmy Kimmel Live! Music</a> — as well as the 30A Songwriter’s Festival in Florida, Wire and Wood Songwriter Festival in Alpharetta, GA, Jammin’ Java Listening Room in Vienna, VA, the Elbo Room in Chicago, IL and Eddie’s Attic in Atlanta, GA.<p>In the early stages of his career, Guthrie released his first album, <em>Lessons Learned, </em>and also scored the Atlanta Braves Band of the Year in 2014. In 2015, Guthrie and his band were awarded the Georgia Americana Artist of the Year — another astounding achievement bringing his music much-deserved attention and recognition. Within a short span of time, Guthrie was opening up for national touring artists including renowned BMLG Records recording Artist Drake White, RCA recording artist Bleachers, and famous Atlantic Records recording Artist Kelly Clarkson.<p>Singer-songwriter Alex Guthrie continues to impress and defy conventional expectations, making waves as he makes great music. A new album is currently being recorded and is expected to be released in Spring 2018.<p><p><a href=\"http://www.workplay.com/wp-content/uploads/2018/02/IMG_9283.jpg\" rel=\"nofollow\"></a>Born in the Philippines, raised in New York, educated in California and now entertaining Birmingham, AL, is one of the hottest musicians rising out of the growing music scene. Lily has built a buzz beyond just Birmingham, and many of those who follow the local music scene mention her as one of those Birmingham gems that is poised to explode onto the national and international scene. Her music mixes R&B, jazz, pop, folk and funk with her superb songwriting talents. She has played venues all over the country and remains busy with an enormous following on newly the emerging streaming platform, Twitch, and YouTube. She is looking to release a new album this year, and has recently released a video for her single, “<a href=\"https://www.youtube.com/watch?v=pYYQNdhzxoQ\" rel=\"nofollow\">Tinder Love</a>”</p></p></p></p></p></p></p></p>",
                "modified": "2018-04-14 15:15:45",
                "venue_display": "1",
                "performers": null,
                "title": "Alex Guthrie w/ Raquel Lily",
                "venue_address": "500 23rd St S",
                "geocode_type": "EVDB Geocoder",
                "owner": "evdb",
                "country_abbr2": "US",
                "image": {
                    "block100": {
                        "width": "100",
                        "url": "//d1marr3m5x4iac.cloudfront.net/images/block100/I0-001/039/894/992-8.jpeg_/alex-guthrie-w-raquel-lily-92.jpeg",
                        "height": "100"
                    },
                    "blackborder250": {
                        "width": "250",
                        "url": "//d1marr3m5x4iac.cloudfront.net/images/blackborder250/I0-001/039/894/992-8.jpeg_/alex-guthrie-w-raquel-lily-92.jpeg",
                        "height": "250"
                    }
                },
                "created": "2018-02-10 18:59:17",
                "venue_id": "V0-001-001125136-2",
                "venue_name": "WorkPlay Theatre",
            },
            {
                "olson_path": "America/Chicago",
                "region_abbr": "AL",
                "postal_code": "35205",
                "latitude": "33.5054018",
                "id": "E0-001-113723650-9",
                "city_name": "Birmingham",
                "longitude": "-86.7904843",
                "country_name": "United States",
                "country_abbr": "USA",
                "region_name": "Alabama",
                "start_time": "2018-06-01 22:00:00",
                "description": " <br> ",
                "modified": "2018-04-20 01:15:57",
                "venue_display": "1",
                "performers": {
                    "performer": {
                        "creator": "sljmee",
                        "linker": "evdb",
                        "name": "Caddle",
                        "url": "http://concerts.eventful.com/Caddle?utm_source=apis&utm_medium=apim&utm_campaign=apic",
                        "id": "P0-001-000041723-6",
                        "short_bio": "rock,country,high octane"
                    }
                },
                "title": "Caddle, Chris Simmons Band, The Edmonds Butler Band, GreenLeaf Hustle",
                "venue_address": "2514 10th Avenue South",
                "geocode_type": "EVDB Geocoder",
                "owner": "evdb",
                "country_abbr2": "US",
                "image": {
                    "block100": {
                        "width": "100",
                        "url": "//d1marr3m5x4iac.cloudfront.net/images/block100/I0-001/000/405/565-4.jpg_/caddle-65.jpg",
                        "height": "100"
                    },
                    "blackborder250": {
                        "width": "250",
                        "url": "//d1marr3m5x4iac.cloudfront.net/images/blackborder250/I0-001/000/405/565-4.jpg_/caddle-65.jpg",
                        "height": "250"
                    }
                },
                "created": "2018-04-14 11:24:40",
                "venue_id": "V0-001-000885124-1",
                "venue_name": "The Nick",
            },
            {
                "olson_path": "America/Chicago",
                "region_abbr": "AL",
                "postal_code": "35222",
                "latitude": "33.524291",
                "id": "E0-001-114192468-3",
                "city_name": "Birmingham",
                "longitude": "-86.7744642",
                "country_name": "United States",
                "country_abbr": "USA",
                "region_name": "Alabama",
                "start_time": "2018-06-23 20:30:00",
                "description": " <br> Sacramento, CA alternative hip-hop artist Hobo Johnson is Frank Lopes Jr; often backed by his bandmates The Lovemakers. In November 2017, Hobo Johnson released the record The Rise of Hobo Johnson, which Frank wrote during a time he had to live out of his &#39;94 Toyota Corolla - hence his self-given pseudonym. On April 17, 2018, Hobo Johnson released the highly-anticipated single &quot;Peach Scone&quot; (both the studio and live version), which debuted on Spotifys New Music Friday. (Listen to &quot;Peach Scone&quot; here.) The new single comes on the heels of Hobo Johnson&#39;s &quot;Peach Scone&quot; live performance video, which was posted online as a submission for NPRs Tiny Desk contest. The live video of that unreleased track got Hobo Johnson much more than expected. In just 7 weeks, the &quot;Peach Scone&quot; video racked up over 14.6 million views on Facebook and YouTube. Across all socials, their followers have grown from 10,000 total to well over one million followers. Their fervent new fans boosted the 2017 The Rise of Hobo Johnson album to #8 on the iTunes Hip-Hop chart and #11 on Billboard&#39;s Heatseekers chart. Hobo Johnson has also caught the attention of big media players like MTV who tweeted &quot;Very much in love with @_hobojohnson&quot; and a feature from Perez Hilton and The Needle Drop. Five different songs from The Rise of Hobo Johnson have charted on Spotify&#39;s Global Viral 50, US Viral 50, Australia Viral 50, UK Viral 50, Canada Viral 50, Philippines Viral 50, Spain Viral 50, NZ Viral 50, Ireland Viral 50, Netherlands Viral 50. It has also appeared on on Spotify&#39;s Tear Drop, Viral Hits Canada, Viral Hits AUS & NZ. This year, fans can look forward to more US and international tour dates from Hobo Johnson & The Lovemakers.",
                "modified": "2018-05-06 11:56:48",
                "venue_display": "1",
                "performers": null,
                "title": "Hobo Johnson",
                "venue_address": "200 41st Street S",
                "geocode_type": "EVDB Geocoder",
                "owner": "evdb",
                "country_abbr2": "US",
                "image": null,
                "created": "2018-05-06 11:56:48",
                "venue_id": "V0-001-008874407-7",
                "venue_name": "Saturn",
            },
            {
                "olson_path": "America/Chicago",
                "region_abbr": "AL",
                "postal_code": "35205",
                "latitude": "33.5054018",
                "id": "E0-001-113055094-1",
                "city_name": "Birmingham",
                "longitude": "-86.7904843",
                "country_name": "United States",
                "country_abbr": "USA",
                "region_name": "Alabama",
                "start_time": "2018-06-08 22:00:00",
                "description": " <br> ",
                "modified": "2018-05-03 11:12:06",
                "venue_display": "1",
                "performers": {
                    "performer": {
                        "creator": "evdb",
                        "linker": "evdb",
                        "name": "VOLK",
                        "url": "http://concerts.eventful.com/VOLK?utm_source=apis&utm_medium=apim&utm_campaign=apic",
                        "id": "P0-001-000267723-0",
                        "short_bio": "Dance / Electronic / Pop"
                    }
                },
                "title": "VOLK, Cahaba, Starship Pilgrims",
                "venue_address": "2514 10th Avenue South",
                "geocode_type": "EVDB Geocoder",
                "owner": "evdb",
                "country_abbr2": "US",
                "image": {
                    "block100": {
                        "width": "100",
                        "url": "//d1marr3m5x4iac.cloudfront.net/images/block100/I0-001/004/340/729-0.jpeg_/volk-29.jpeg",
                        "height": "100"
                    },
                    "blackborder250": {
                        "width": "250",
                        "url": "//d1marr3m5x4iac.cloudfront.net/images/blackborder250/I0-001/004/340/729-0.jpeg_/volk-29.jpeg",
                        "height": "250"
                    }
                },
                "created": "2018-03-21 08:41:43",
                "venue_id": "V0-001-000885124-1",
                "venue_name": "The Nick",
            },
            {
                "olson_path": "America/Chicago",
                "region_abbr": "AL",
                "postal_code": "35205",
                "latitude": "33.497336",
                "url": "http://birmingham.eventful.com/events/artifakts-18-event-/E0-001-114072763-0?utm_source=apis&utm_medium=apim&utm_campaign=apic",
                "id": "E0-001-114072763-0",
                "city_name": "Birmingham",
                "longitude": "-86.793077",
                "country_name": "United States",
                "country_abbr": "USA",
                "region_name": "Alabama",
                "start_time": "2018-06-02 21:30:00",
                "description": null,
                "modified": "2018-05-02 00:54:57",
                "venue_display": "1",
                "performers": null,
                "title": "Artifakts (18+ Event)",
                "venue_address": "2001 15th Avenue South",
                "geocode_type": "EVDB Geocoder",
                "owner": "evdb",
                "country_abbr2": "US",
                "image": null,
                "created": "2018-05-02 00:54:57",
                "venue_id": "V0-001-000508203-5",
                "venue_name": "Zydeco",

            },
            {
                "olson_path": "America/Chicago",
                "region_abbr": "AL",
                "postal_code": "35222",
                "latitude": "33.524291",
                "url": "http://birmingham.eventful.com/events/sam-lewis-/E0-001-112765245-2?utm_source=apis&utm_medium=apim&utm_campaign=apic",
                "id": "E0-001-112765245-2",
                "city_name": "Birmingham",
                "longitude": "-86.7744642",
                "country_name": "United States",
                "country_abbr": "USA",
                "region_name": "Alabama",
                "start_time": "2018-06-22 21:00:00",
                "description": " <br> Like many before him, Sam Lewis came to Nashville to make music. But unlike the majority, Lewis managed to hop on one of the most successful tours that country music has seen as of late. He&#39;s collaborated with everyone from John Prine and Kacey Musgraves to The Wood Brothers. Chris Stapleton dubbed him &quot;a modern Townes Van Zandt&quot;. And while he&#39;s often labeled with some form of the word &#39;soulful&#39; (some have even compared his voice to molasses), Lewis&#39; style meets at a juncture of many different genres. There&#39;s something about Sam Lewis that is indescribably different -- and with his newest project, he&#39;s discovered what most musicians spend lifetimes working for -- the place where feel-good music meets vital social commentary. When Lewis decided to make the move from Knoxville to Nashville in summer 2009, he was still working full-time at Walmart (a gig that lasted nearly a decade). In his off-time, he began playing smaller local venues including the 5 Spot, where he met fel- low singer-songwriter Matt Urmy. After forming a friendship, Urmy offered to help Lewis &quot;We went to his basement, I laid down some songs, we pieced a band together and made a record in a couple days at Eastwood Studios.&quot; That record would become Lewis&#39;s first official release and self-titled debut that featured Nashville greats Kenny Vaughan, Reggie Bradley Smith, Dave Jacques, and Derek Mixon. And with Lewis&#39; sole intention of moving to be a musician that &#39;records it and tours it&#39; - he did just that - traveling from Nashville to New York via train to play shows, then spending a month in England. By late 2014, Lewis had turned 30, established himself with the Nashville music scene, and signed with the boutique Georgia label, Brash Records. With the help of Brash and producer Oliver Wood of The Wood Brothers, Lewis released his second full- length, Waiting on You, in April 2015. The sophomore was critically acclaimed and once again featured Kenny Vaughan, in addition to Darrell Scott, Gabe Dixon, the McCrary Sisters, and Willie Nelson&#39;s legendary harmonica player, Mickey Raphael. While No De- pression compared Lewis&#39; soulful style with the likes of Al Green and Van Morrison, Craig Havighurst (Music City Roots) coined Waiting on You as &quot;Americana with a groovy twist&quot;. While the album racked in incredible reviews, Lewis&#39; booking agency also got bought out in the same time frame - unfortunately leaving him with a solid album, but no tour dates to show for it.Lewis applied to work at a Post Office in East Nashville but by the time he got a call for a second interview, someone else had called with a more enticing offer: the open- ing spot for the Traveler release show, Chris Stapleton&#39;s Grammy-winning album. From there, life moved fast. Lewis toured with Stapleton for the remainder of summer 2015, and by January 2016, found himself playing sold-out 2 and 3-night shows at venues like The Tabernacle and the Ryman Auditorium.During that time, Lewis was driving to play a show in Richmond when he spotted a bright, rainbow building just off the interstate. &quot;The building had a word on it, but all I could see was -SITY,&quot; he says, &quot;I immediately said &#39;loversity&#39;, even though the sign said &#39;di- versity&#39;. My friend and I Googled it and it wasn&#39;t a real word, but I thought, well, I like that word.&quot; A week later, Lewis returned home and immediately wrote &quot;Loversity&quot;, which would set the tone for his album.Lewis&#39; forthcoming record Loversity is set to be released on May 4, 2018. The album is composed of 14 tracks that Lewis has spent over a year and a half writing and playing for others. Since Waiting on You, his classic style remains present yet matured, with a more re- fined worldview, &quot;These newer songs have been harder to write, but extremely necessary given the current climate I find the world in.&quot; Recorded at Southern Ground Studios with engineer and co-producer Brandon Bell, the album spans from upbeat songs like the title track &quot;Loversity&quot; to the darker &quot;One in the Same,&quot; an electric guitar heavy ballad with a dri- ving force reminiscent of the Black Keys&#39; Brothers. While most songs are originals, the record includes &quot;Accidental Harmony&quot;, a lullaby that fellow Nashville songwriter John Mann wrote for his first born child, and &quot;Natural Disaster&quot;, a Loudon Wainwright song that Lewis felt drawn to.And while each song varies in tone, they all circle back to one universal theme. &quot;This is the closest thing I&#39;ll ever write to a concept album. The idea is that we are all trying to get somewhere -- all running from something and toward something. We&#39;re all together in it, though.&quot; As current events in the world divide the masses based on difference, Sam Lewis&#39; new album is a soul-filled, catchy collection of reminders that diversity and unity can co-exist.",
                "modified": "2018-03-13 13:57:57",
                "venue_display": "1",
                "performers": null,
                "title": "Sam Lewis",
                "venue_address": "200 41st Street S",
                "geocode_type": "EVDB Geocoder",
                "owner": "evdb",
                "country_abbr2": "US",
                "image": null,
                "created": "2018-03-13 13:57:57",
                "venue_id": "V0-001-008874407-7",
                "venue_name": "Saturn",
            },
            {
                "olson_path": "America/Chicago",
                "region_abbr": "AL",
                "postal_code": "35233",
                "latitude": "33.509863",
                "id": "E0-001-112335335-9",
                "city_name": "Birmingham",
                "longitude": "-86.7975619",
                "country_name": "United States",
                "country_abbr": "USA",
                "region_name": "Alabama",
                "start_time": "2018-06-09 18:00:00",
                "description": " <p>Come arouse your senses with the visual and physical experience that is the Birmingham Erotic Art Party! Artist and vendors from all around will fill the space with Erotic art featuring local artists and entertainment, featuring burlesque performances by Pink Box Burlesque and Birmingham’s belly dancing tribes, shibari and live fire dancing. Artists and vendors will include body painting, body henna, budoir photography sessions, paintings, statues, mixed media art, soy candles, body scrubs and tarot readings,<p>Experience a different show every 30 minutes and top off the night dancing your heart out on the floor with special guest DJ’s!<p>The entire event will blow your mind including visual lighting and effects by Birmingham’s Illuminature!<br><strong><a href=\"http://www.workplay.com/wp-content/uploads/2018/03/bham-erotic-party.jpg\" rel=\"nofollow\"></a></strong><br><p></p></p></p></p>",
                "modified": "2018-03-03 17:04:25",
                "venue_display": "1",
                "performers": null,
                "title": "Birmingham Erotic Art Party",
                "venue_address": "500 23rd St S",
                "geocode_type": "EVDB Geocoder",
                "owner": "evdb",
                "country_abbr2": "US",
                "image": {
                    "block100": {
                        "width": "100",
                        "url": "//d1marr3m5x4iac.cloudfront.net/images/block100/I0-001/039/936/963-3.jpeg_/birmingham-erotic-art-party-63.jpeg",
                        "height": "100"
                    },
                    "blackborder250": {
                        "width": "250",
                        "url": "//d1marr3m5x4iac.cloudfront.net/images/blackborder250/I0-001/039/936/963-3.jpeg_/birmingham-erotic-art-party-63.jpeg",
                        "height": "250"
                    }
                },
                "created": "2018-03-03 12:17:25",
                "venue_id": "V0-001-001125136-2",
                "venue_name": "WorkPlay Theatre",
            },
            {
                "olson_path": "America/Chicago",
                "region_abbr": "AL",
                "postal_code": "35205",
                "latitude": "33.500174",
                "id": "E0-001-113674012-0",
                "city_name": "Birmingham",
                "longitude": "-86.799373",
                "country_name": "United States",
                "country_abbr": "USA",
                "region_name": "Alabama",
                "start_time": "2018-06-01 23:00:00",
                "description": null,
                "modified": "2018-05-15 20:44:36",
                "venue_display": "1",
                "performers": null,
                "title": "Steel City Jug Slammers- Spearman Brewers",
                "venue_address": "1813 10th Court South",
                "geocode_type": "EVDB Geocoder",
                "owner": "evdb",
                "country_abbr2": "US",
                "image": null,
                "created": "2018-04-11 16:30:03",
                "venue_id": "V0-001-001375045-0",
                "venue_name": "Martys",

            }
]
